version: "3"

services:
  app: 
    build: .
    command: npm run dev-docker
    container_name: encartecontainer
    restart: always
    ports: 
        - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    container_name: pgencarte
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    extra_hosts:
      - "pgmaster:10.0.0.3"